### ISSUE TITLE
HDR Tone Mapping - Green Line

### ISSUE THREAD

**Issue by parasupaman** [rigaya/QSVEnc#59]
I have been doing a few HDR2SDR tone mapped encodes, which have worked excellent, great work!

The only small issue that I just noticed is a **thin green line** running across the bottom of the frame.   I went back to check each encode that I have done and notice that this occurs on **every** single HDR2SDR encode.  Hopefully this bug is not too difficult to find.

**EXAMPLE** _(click on the image below to more easily see the green line)_:
![HDR2SDR Green Line](https://user-images.githubusercontent.com/77555688/123889681-5c7f4380-d999-11eb-96ad-d897b7c654f4.jpg)

```
D:\MKV>QSVEncC64.exe --avhw --fps 24000/1001 --codec hevc --sar 1:1 --qp-offset 2:6:8 --async-depth 2 --no-deblock --ref 6 --bframes 7 --b-pyramid --gop-len 240 --weightp --weightb --fade-detect --vpp-colorspace hdr2sdr=bt2390,source_peak=1000 --crop 0,0,0,0 --cqp 17:18:20 --quality best --input-file ATest.hevc --output-file ATest.hevc.hevc
--------------------------------------------------------------------------------
ATest.hevc.hevc
--------------------------------------------------------------------------------
cop3.DirectBiasAdjustment value changed off -> auto by driver
cop3.GlobalMotionBiasAdjustment value changed off -> auto by driver
QSVEncC (x64) 5.05 (r2369) by rigaya, Jun 12 2021 12:48:47 (VC 1928/Win)
OS             Windows 10 x64 (19043) [UTF-8]
CPU Info       11th Gen Intel Core i7-1165G7 @ 2.80GHz [TB: 4.10GHz] (4C/8T) <Tigerlake>
GPU Info       Intel Iris(R) Xe Graphics (96EU) 100-1300MHz [28W] (27.20.100.9466)
Media SDK      QuickSyncVideo (hardware encoder) PG, 1st GPU, API v1.34
Async Depth    2 frames
Buffer Memory  d3d11, 31 work buffer
Input Info     avqsv: H.265/HEVC, 3840x1606, 24000/1001 fps
VPP            cspconv(p010 -> yv12)
               colorspace: cspconv(yv12 -> yuv444)
                           matrix:bt2020nc->GBR
                           transfer:smpte2084->linear
                           hdr2sdr(bt2390): source_peak=1000.00 ldr_nits=100.00
                             desat base 0.18, strength 0.75, exp 1.50
                           prim:bt2020->bt709
                           transfer:linear->bt709
                           matrix:GBR->bt709
               cspconv(yuv444 -> nv12)
AVSync         cfr
Output         HEVC(yuv420) main @ Level 5 (high tier)
               3840x1606p 1:1 23.976fps (24000/1001fps)
Target usage   1 - best
Encode Mode    Constant QP (CQP)
CQP Value      I:17  P:18  B:20
QP Limit       min: 1, max: 51
Trellis        Auto
Ref frames     6 frames
Bframes        7 frames, B-pyramid: on
Max GOP Length 240 frames
Ext. Features  No-Deblock WeightP WeightB FadeDetect QPOffset tskip ctu:64 sao:all
```

**Comment by rigaya** [comment]
Thanks for letting me know the issue, I think I've found what is causing this problem.

I'll have it fixed in the next release.

**Comment by rigaya** [comment]
I have updated QSVEnc to [5.06](https://github.com/rigaya/QSVEnc/releases/tag/5.06), the issue shall be fixed in this version.

**Comment by parasupaman** [comment]
> I have updated QSVEnc to [5.06](https://github.com/rigaya/QSVEnc/releases/tag/5.06), the issue shall be fixed in this version.

I just tested it and the green line appears to have been fixed.  Excellent, thanks very much!

**Comment by parasupaman** [comment]
Unfortunately, I forgot to Crop when testing.  Green line issue still exists when cropping.  In this image, I cropped 42 pixels top and bottom.

![image](https://user-images.githubusercontent.com/77555688/127089183-34177d05-69e5-475d-84f6-76dffee18f33.png)

**Comment by rigaya** [comment]
I've tried another fix on [QSVEnc 6.00](https://github.com/rigaya/QSVEnc/releases/tag/6.00), which won't have this issue even if we add cropping.

**Comment by parasupaman** [comment]
Thanks for trying a fix.  Unfortunately, cropping still appears to have the same green line issue:

![HDR2SDR Cropped](https://user-images.githubusercontent.com/77555688/132119058-a224d2b6-914a-40e3-9d5d-2ab8fca25eb8.jpg)


```
cop3.DirectBiasAdjustment value changed off -> auto by driver
cop3.GlobalMotionBiasAdjustment value changed off -> auto by driver
QSVEncC (x64) 6.00 (r2453) by rigaya, Sep  5 2021 01:48:17 (VC 1929/Win)
OS             Windows 10 x64 (19043) [UTF-8]
CPU Info       11th Gen Intel Core i7-1165G7 @ 2.80GHz [TB: 4.10GHz] (4C/8T) <Tigerlake>
GPU Info       Intel Iris(R) Xe Graphics (96EU) 100-1300MHz [28W] (30.0.100.9805)
Media SDK      QuickSyncVideo (hardware encoder) PG, 1st GPU, API v2.03
Async Depth    2 frames
Buffer Memory  d3d11, 30 work buffer
Input Info     avqsv: H.265/HEVC, 3840x2160, 24000/1001 fps
VPP            crop: 0,276,0,276/cspconv(p010 -> yv12)
               colorspace: cspconv(yv12 -> yuv444)
                           matrix:bt2020nc->GBR
                           transfer:smpte2084->linear
                           hdr2sdr(bt2390): source_peak=4000.00 ldr_nits=100.00
                             desat base 0.18, strength 0.75, exp 1.50
                           prim:bt2020->bt709
                           transfer:linear->bt709
                           matrix:GBR->bt709
               cspconv(yuv444 -> nv12)
AVSync         cfr
Output         HEVC(yuv420) main @ Level 5 (high tier)
               3840x1608p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc => matroska
Target usage   4 - balanced
Encode Mode    Constant QP (CQP)
CQP Value      I:16  P:17  B:19
QP Limit       min: 1, max: 51
Trellis        Auto
Ref frames     6 frames
Bframes        7 frames, B-pyramid: on
Max GOP Length 240 frames
Ext. Features  WeightP WeightB FadeDetect QPOffset
Break in task OPENCL: operation aborted..9%, VD 16%

encoded 3087 frames, 27.17 fps, 23425.58 kbps, 359.55 MB
encode time 0:01:53, CPU: 12.5%, GPU: 99.1%, VD: 16.5%
frame type IDR   13
frame type I     13,  total size    6.14 MB
frame type P    386,  total size  144.04 MB
frame type B   2688,  total size  209.37 MB
```

**Comment by rigaya** [comment]
[QSVEnc 6.01](https://github.com/rigaya/QSVEnc/releases/tag/6.01) adds another fix for this.

**Comment by parasupaman** [comment]
Hey, looks like you were finally able to track down the issue!  Great job!  Just tested with cropping and looks fine now:

![HDR2SDR Cropped](https://user-images.githubusercontent.com/77555688/132259126-53797dd2-b557-4b00-adf7-e3dcaf25f80d.jpg)
